name: sportguider
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  google_fonts: ^6.1.0
  yandex_mapkit: ^4.2.1
  auto_route: ^11.0.0 
  salomon_bottom_bar: ^3.1.0
  permission_handler: ^12.0.1
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_svg: ^2.2.3
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
